# U.T.6 Redes Neuronales.
## Tensorflow
### Introducción
Tensorflow es una librería escalable para la programación de machine Learning desarrollada por Google y liberada en 2015.
Con la versión 2 de la librería se está convirtiendo en el estándar para el ML al simplificar mucho su uso

La principal ventaja es que es eficiente sobre cualquier tipo de procesador, incluso con estructuras distribuidas.
Esta librería hace un uso eficiente de las GPU de nuestra máquina si ésta tiene núcleos CUDA o TPUs así como clusters o
cualquier estructura hardware de computación

Es imprescindible tener una GPU para ML si queremos realizar algoritmos decentes. Una estimación: en una CPU normal
actual puede tardar una semana en compilarse una modelo, con una RTX 2080Ti tardará unas horas.
Otra opción es usar los servicios distribuidos para ML Learning de Google, Keras, Microsoft, etc…

### Instalación y configuración
pip install tensorflow

https://docs.nvidia.com/cuda/index.html#installation-guides

### Estructura
![](img/ut06_24.png)

### Operaciones básicas

In [ ]:
#  Inicio
import tensorflow as tf
import numpy as np

print('TensorFlow version:', tf.__version__)  # 2.3.1
a = np.array([1, 2, 3], dtype=np.int32)   # Definimos un array numpy
b = [4, 5, 6]  # Definimos una lista
#  Creamos los tensores correspondientes
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)
print(t_a)  # tf.Tensor([1 2 3], shape=(3,), dtype=int32)
print(t_b)  # tf.Tensor([4 5 6], shape=(3,), dtype=int32)

#  Comprobamos si son tensores dos variables
print(tf.is_tensor(a), tf.is_tensor(t_a))  # False True

#  Creamos un tensor bidimensional relleno de unos
t_ones = tf.ones((2, 3))
print(t_ones.shape)  # (2, 3)

# Accedemos al array de numpy del tensor
print(t_ones.numpy())

#  Creamos un tensor constante, con tres valores de rango uno.
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)
print(const_tensor)

# Conversiones entre NumpPy
print(type(t_ones.numpy()))  # <class 'numpy.ndarray'>
print(type(np.array(t_ones)))  # <class 'numpy.ndarray'>

### Acceso a los datos indexados

In [ ]:
print(t_ones[:, 1:])
print(t_ones[..., 1, tf.newaxis])
print(t_a + 10)  # tf.Tensor([11 12 13], shape=(3,), dtype=int32)
print(tf.square(t_a))  # tf.Tensor([1 4 9], shape=(3,), dtype=int32)
print(t_ones @ tf.transpose(t_ones))  # @ equivalente a tf.matmul()

### Manejo del tipo de los datos y su dimensión

In [ ]:
t_a_new = tf.cast(t_a, tf.int64)  # Cambiamos el tipo a int64 del tensor t_a
print(t_a_new.dtype)  # <dtype: 'int64'>
t = tf.random.uniform(shape=(3, 5))  # los elementos en una matriz de 3 por 5
t_tr = tf.transpose(t)  # Hacemos la transpuesta
print(t.shape, ' --> ', t_tr.shape)  # (3, 5)  -->  (5, 3)
t = tf.zeros((30,))  # Creamos un tensor de rango 1 con 30 ceros
t_reshape = tf.reshape(t, shape=(5, 6))  # un tensor de rango 2 de 5 por 6
print(t_reshape.shape)  # (5, 6)
t = tf.zeros((3, 2, 1, 4, 1))  # Tensor 5 dimensiones, cada uno con 3,2,1,4,1 ceros


### Eliminamos la tercera y la quinta dimensión, se empieza en cero

In [ ]:
t_sqz = tf.squeeze(t, axis=(2, 4))
print(t.shape, ' --> ', t_sqz.shape)  # (3, 2, 1, 4, 1)  -->  (3, 2, 4)

### Operaciones matemáticas

In [ ]:
tf.random.set_seed(1)
t1 = tf.random.uniform(shape=(5, 2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5, 2),  mean=0.0, stddev=1.0)
print(t1, t2)
t3 = tf.multiply(t1, t2).numpy()
t4_a = tf.math.reduce_mean(t1, axis=0)  # por columnas axis=0
t4_b = tf.math.reduce_mean(t1, axis=1)  # por filas axis=1
t5 = tf.linalg.matmul(t1, t2, transpose_b=True)
print(t5.numpy())
t6 = tf.linalg.matmul(t1, t2, transpose_a=True)
print(t6.numpy())
norm_t1 = tf.norm(t1, ord=2, axis=1).numpy()
print(norm_t1)
print(np.sqrt(np.sum(np.square(t1), axis=1)))  # Por filas axis=1
print(np.sqrt(np.sum(np.square(t1), axis=0)))  # Por columnas axis=0

In [ ]:
### Variales y constantes
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v.assign(2 * v)
print(v)  # => [[2., 4., 6.], [8., 10., 12.]]
v[0, 1].assign(42)
print(v)  # => [[2., 42., 6.], [8., 10., 12.]]
v[:, 2].assign([0., 1.])
print(v)  # => [[2., 42., 0.], [8., 10., 1.]]
v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.])
print(v)  # => [[100., 42., 0.], [8., 10., 200.]]

a = tf.Variable(initial_value=3.14, name='var_a')
b = tf.Variable(initial_value=[1, 2, 3], name='var_b')
c = tf.Variable(initial_value=[True, False], dtype=tf.bool)
d = tf.Variable(initial_value=['abc'], dtype=tf.string)

w = tf.Variable([1, 2, 3], trainable=False)
print(w.assign([3, 1, 4], read_value=True))
w.assign_add([2, -1, 2], read_value=False)

init = tf.keras.initializers.GlorotNormal()
w = tf.Variable(init(shape=(2, 3)))
w = tf.Variable(tf.random.uniform((3, 3)))

ct = tf.constant([1, 2, 3])
print(ct)  # tf.Tensor([1 2 3], shape=(3,), dtype=int32)

### Divisiones e uniones

In [ ]:
tf.random.set_seed(1)
t = tf.random.uniform((6,))
print(t.numpy())

t_splits = tf.split(t, 3)   # Dividimos en bloques de tres
for item in t_splits:
    print(item.numpy())
tf.random.set_seed(1)
t = tf.random.uniform((5,))
print(t.numpy())

t_splits = tf.split(t, num_or_size_splits=[3, 2])
for item in t_splits:
    print(item.numpy())
A = tf.ones((3,))
B = tf.zeros((2,))
C = tf.concat([A, B], axis=0)
print(C.numpy())  # [1. 1. 1. 0. 0.]
A = tf.ones((3,))
B = tf.zeros((3,))
S = tf.stack([A, B], axis=0)   # Por columnas axis=0
print(S.numpy())
S = tf.stack([A, B], axis=1)  # Por filas axis=1
print(S.numpy())

### Funciones

In [ ]:
@tf.function
def compute_z(a, b, c):
    r1 = tf.subtract(a, b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z

tf.print('Scalar Inputs:', compute_z(1, 2, 3))
tf.print('Rank 1 Inputs:', compute_z([1], [2], [3]))
tf.print('Rank 2 Inputs:', compute_z([[1]], [[2]], [[3]]))

### Normas al crear funciones
- Un gráfico solo puede tener llamadas a otras funciones de TensorFlow.
- Se pueden llamar a otras funciones Python si solo tienen código TensorFlow.
- Si se crean variables deben ser las primeras líneas, o mejor hacerlas fuera de la función.
- Se debe proporcionar el código fuente de forma externa para que funcione, no se puede dar código Python compilado.
- Los bucles for de Python solo se capturarán si son sobre Dataset o Tensores (usar tf.range en vez de range).
- Usar versiones vectorizadas de las operaciones mejores que los bucles al mejorar la eficiencia.

### Uso de hardware avanzado
En caso que tengamos una tarjeta gráfica con una GPU habilitada para ML podremos hacer uso de todas las aceleraciones
existentes, pero para ello deberá ser compatible con NVIDIA y tener instalado el Toolkit CUDA, la librería NVIDIA
cuDNN

https://docs.nvidia.com/cuda/index.html#installation-guides

Para saber a qué dispositivos están asignados sus operaciones y tensores, hay que colocar
tf.debugging.set_log_device_placement(True) como la primera declaración de su programa. Al habilitar el
registro de ubicación de dispositivos, se imprimen las asignaciones u operaciones de Tensor.

https://www.tensorflow.org/guide/gpu

### Uso de TPUs
Las TPU son unidades hardware desarrolladas específicamente para el entrenamiento de redes neuronales por Google.
El soporte experimental para Cloud TPU actualmente está disponible para Keras y Google Colab.

https://www.tensorflow.org/guide/tpu

### Uso de la nube
TensorFlow Cloud es un paquete de Python que proporciona API para una transición perfecta de la depuración local al
entrenamiento distribuido en Google Cloud. Simplifica el proceso de entrenamiento de modelos de TensorFlow en la nube
en una única llamada, que requiere una configuración mínima y sin cambios en su modelo. TensorFlow Cloud maneja tareas
específicas de la nube, como crear instancias de VM y estrategias de distribución para sus modelos automáticamente.

https://www.tensorflow.org/guide/keras/training_keras_models_on_cloud

https://github.com/tensorflow/cloud/blob/master/src/python/tensorflow_cloud/core/tests/examples/dogs_classification.ipynb

https://www.tensorflow.org/guide/distributed_training